global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cumulus3'
    static_configs:
      - targets: ['cumulus3:8800']
    metrics_path: '/metrics'
    scrape_interval: 10s
